<<<<<<< HEAD
title: Logging and Debugging with Azure Bot Service
description: Microsoft labs for learning to log and debugg with Azure Bot Service
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/learnAnalytics-AdvancedFeaturesforMicrosoftBotFramework
=======
title: Learn AI Bootcamp Materials
description: Microsoft labs for learning to develop AI-oriented applications.
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/LearnAI-Bootcamp
>>>>>>> his1
