title: Logging and Debugging with Azure Bot Service
description: Microsoft labs for learning to log and debugg with Azure Bot Service
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/learnAnalytics-AdvancedFeaturesforMicrosoftBotFramework